### ISSUE TITLE
The package name should be something else

### ISSUE THREAD

**Issue by ayushpatnaikgit** [bschneidr/fastsurvey#6]
The package name is `survey`. It's a bit of an issue if you want Lumley's survey and your package at the same time. How about changing it to something else, like `fastsurvey`?

**Comment by bschneidr** [comment]
I left the package name as is because it was helpful for work developing this as something that might eventually be incorporated into the survey package. I'll make a branch with the package renamed when I return from vacation.

**Comment by bschneidr** [comment]
@ayushpatnaikgit  Please see the branch titled "renamed-package":
https://github.com/bschneidr/fastsurvey/tree/renamed-package
